---
title: "salmon_group17"
author: "Kat Leigh, Teague Tran, Lucas Empson"
date: "1/29/2021"
output: 
  html_document:
    css: "style.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

#load packages to wrangle salmon data 

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(tsibble)
library(feasts)
library(slider)

#read in data for all of statistics and visualizations
salmon <- read_csv(here("data", "willamette_fish_passage.csv")) %>% 
  # clean up column names to make data wrangling easier
  clean_names()
  #replace NAs with 0
salmon[is.na(salmon)] = 0

```

```{r, message = FALSE, warning = FALSE}
#data wrangling to select species and get dates
selectedsalmonid <- salmon %>% 
  select("project", "date", "chinook", "jack_coho", "steelhead") %>% 
  mutate(new_date = mdy(date)) %>% 
  as_tsibble(key = NULL, index = new_date)
```

```{r}
#data wrangling for tab 3 (Teague)
#sum all steelhead per year 
steelhead_year <- selectedsalmonid %>% 
  index_by(year = ~year(.)) %>% 
  summarize(annual_steelhead = sum(steelhead))
#visualize all steelhead per year
ggplot(data = steelhead_year, aes(x = year, y = annual_steelhead)) + 
  geom_line()
#sum all chinook per year
chinook_year <- selectedsalmonid %>% 
  index_by(year = ~year(.)) %>% 
  summarize(annual_chinook = sum(chinook))
#visualize all chinook per year
ggplot(data = chinook_year, aes(x = year, y = annual_chinook)) + 
  geom_line()
#sum all jack coho a year
jack_coho_year <- selectedsalmonid %>% 
  index_by(year = ~year(.)) %>% 
  summarize(annual_jack_coho = sum(jack_coho))
#visualize all jack coho a year
ggplot(data = jack_coho_year, aes(x = year, y = annual_jack_coho)) + 
  geom_line()

#merge all of the separate counts into one dataframe
salmonid_year <-merge(steelhead_year, chinook_year, by = "year")
#merge function only allows me to merge 2 dataframes at a time 
total_salmonids_year <- merge(salmonid_year, jack_coho_year, by = "year")

#graph all of the counts on a single plot
ggplot(data = total_salmonids_year) + 
  geom_line(aes(x = year, y = annual_steelhead),  color = "blue") +
  geom_line(aes(x = year, y = annual_chinook), color = "red") +
  geom_line(aes(x = year, y = annual_jack_coho), color = "dark green") 
  
```

